Repository CoinFabrik/scout-soroban, pull requests merged in 2024-04, with the labels that each got.

#89 88 correct soroban version documentation
  README.md
  test-cases/README.md
Labels: documentation

#104 103 improve divide before multiply detector documentation
  detectors/divide-before-multiply/README.md
  detectors/divide-before-multiply/src/lib.rs
Labels: documentation

#118 108 migrate documentation to docusaurus
  README.md
  detectors/README.md
  docs/.gitignore
  docs/babel.config.js
  docs/blog/2019-05-28-first-blog-post.md
  docs/blog/2019-05-29-long-blog-post.md
  docs/blog/2021-08-01-mdx-blog-post.mdx
  docs/blog/2021-08-26-welcome/docusaurus-plushie-banner.jpeg
  docs/blog/2021-08-26-welcome/index.md
  docs/blog/authors.yml
  docs/docs/architecture.md
  docs/docs/contribute.md
  docs/docs/detectors/1-divide-before-multiply.md
  docs/docs/detectors/10-avoid-unsafe-block.md
  docs/docs/detectors/11-dos-unbounded-operation.md
  docs/docs/detectors/12-soroban-version.md
  docs/docs/detectors/13-unused-return-enum.md
  docs/docs/detectors/2-unsafe-unwrap.md
  docs/docs/detectors/3-unsafe-expect.md
  docs/docs/detectors/4-overflow-check.md
  docs/docs/detectors/5-insufficiently-random-values.md
  docs/docs/detectors/6-unprotected-update-current-contract-wasm.md
  docs/docs/detectors/7-avoid-core-mem-forget.md
  docs/docs/detectors/8-set-contract-storage.md
  docs/docs/detectors/9-avoid-panic-error.md
  docs/docs/detectors/README.md
  docs/docs/intro.md
  docs/docs/vulnerabilities/README.md
  docs/docusaurus.config.js
  docs/package.json
  docs/pnpm-lock.yaml
  docs/sidebars.js
  docs/src/components/HomepageFeatures/index.tsx
  docs/src/components/HomepageFeatures/styles.module.css
  docs/src/css/custom.css
  docs/src/pages/about.js
  docs/src/pages/acknowledgements.js
  docs/src/pages/index.module.css
  docs/src/pages/index.tsx
  docs/src/pages/markdown-page.md
  docs/static/.nojekyll
  docs/static/img/aleph-zero.png
  docs/static/img/docusaurus-social-card.jpg
  docs/static/img/docusaurus.png
  docs/static/img/favicon.ico
  docs/static/img/html.png
  docs/static/img/logo.svg
  docs/static/img/scout-social-card.jpg
  docs/static/img/scout.png
  docs/static/img/scout.svg
  docs/static/img/scout_research.svg
  docs/static/img/scout_security.svg
  docs/static/img/scout_tool.svg
  docs/static/img/stellar.png
  docs/static/img/undraw_docusaurus_mountain.svg
  docs/static/img/undraw_docusaurus_react.svg
  docs/static/img/undraw_docusaurus_tree.svg
  docs/static/img/web3-foundation.png
  docs/tsconfig.json
  test-cases/README.md
Labels: documentation

#135 132 ignore docs on ci
  .github/workflows/general-rust.yml
  .github/workflows/test-detectors.yml
  Makefile
Labels: bug

#130 129 remove cli options from main readmemd
  README.md
  detectors/assert-violation/README.md
  detectors/avoid-panic-error/src/README.md
Labels: documentation

#124 117 add detector and test case templates
  templates/detector/early-lint/Cargo.toml
  templates/detector/early-lint/src/lib.rs
  templates/detector/late-lint/Cargo.toml
  templates/detector/late-lint/src/lib.rs
  templates/test-case/Cargo.toml
  templates/test-case/src/lib.rs
Labels: documentation

#139 Try fix CI
  .github/workflows/general-rust.yml
  .github/workflows/test-detectors.yml
Labels: bug

#142 128 improve unprotected update current contract wasm detector
  detectors/unprotected-update-current-contract-wasm/Cargo.toml
  detectors/unprotected-update-current-contract-wasm/src/lib.rs
  test-cases/unprotected-update-current-contract-wasm/unprotected-update-current-contract-wasm-2/remediated-example/Cargo.toml
  test-cases/unprotected-update-current-contract-wasm/unprotected-update-current-contract-wasm-2/remediated-example/src/lib.rs
  test-cases/unprotected-update-current-contract-wasm/unprotected-update-current-contract-wasm-2/vulnerable-example/Cargo.toml
  test-cases/unprotected-update-current-contract-wasm/unprotected-update-current-contract-wasm-2/vulnerable-example/src/lib.rs
  utils/Cargo.lock
  utils/Cargo.toml
  utils/rust-toolchain
  utils/src/lib.rs
  utils/src/soroban_utils/mod.rs
Labels: enhancement

#136 Add iterators over indexing documentation in docusaurs and table
  README.md
  docs/docs/detectors/14-iterators-over-indexing.md
  docs/docs/vulnerabilities/README.md
Labels: documentation

#134 122 write assert violation documentation
  README.md
  detectors/unprotected-mapping-operation/README.md
  docs/docs/detectors/15-assert-violation.md
  docs/docs/vulnerabilities/README.md
Labels: documentation

#133 131 update documentation for unprotected mapping operation
  README.md
  docs/docs/detectors/16-unprotected-mapping-operation
  docs/docs/vulnerabilities/README.md
Labels: documentation

#161 156 add documentation unexpeted revert with vector
  README.md
  docs/docs/detectors/17-dos-unexpected-revert-with-vector.md
  docs/docs/vulnerabilities/README.md
Labels: documentation

#162 157 add documentation unrestricted transfer from
  README.md
  docs/docs/detectors/18-unrestricted-transfer-from.md
  docs/docs/vulnerabilities/README.md
Labels: documentation

#165 158 add documentation for unsafe map get
  README.md
  docs/docs/detectors/19-unsafe-map-get.md
  docs/docs/vulnerabilities/README.md
Labels: documentation

#164 163 add documentation for zero or test address
  README.md
  docs/docs/detectors/20-zero-or-test-address
  docs/docs/vulnerabilities/README.md
Labels: documentation

#174 168 add vulnerability documentation for 2 unsafe unwrap
  docs/docs/vulnerabilities/2-unsafe-unwrap.md
Labels: documentation

#175 Add vulnerability documentation for 1-divide-before-multiply #166
  docs/docs/vulnerabilities/1-divide-before-multiply.md
Labels: enhancement

#177 170-add-vulnerability-documentation-for-4-overflow-check
  docs/docs/vulnerabilities/4-overflow-check.md
Labels: documentation

#178 172-add-vulnerability-documentation-for-6-unprotected-update-current-contract-wasm
  docs/docs/vulnerabilities/6-unprotected-update-current-contract-wasm.md
Labels: documentation

#179 Precision and recall report
  docs/docs/precision-and-recall/first-iteration.md
Labels: documentation

#187 183 add vulnerabiity documentation for avoid unsafe block
  docs/docs/vulnerabilities/10-avoid-unsafe-block.md
Labels: documentation

#186 184 add vulnerability documentation for set contract storage
  docs/docs/vulnerabilities/8-set-contract-storage.md
Labels: documentation
